image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY"/$CI_REGISTRY_IMAGE:latest .
    - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push "$CI_REGISTRY"/$CI_REGISTRY_IMAGE:latest

    